### PR TITLE
DB connection configuration as connection string

### PR DESCRIPTION
**Pull request by he8us**
Hello,

In one of my project, the only way to setup the database configuration is to use a database connection string like `mysql://user:password@mysql.dev:12345/ghost`

To run this project have written some kind of hack to configure Ghost and Knex Migrator. This PR is the fix I need to remove that hack from Knex Migrator.

Since I didn't found Coding Standards for this repo, please let me know if you have suggestions on how to improve the code.

Have a good day,
he8us

### CODE REVIEW

**Comment by kirrg001** [comment]
Hey!

Did you test or consider any existing libraries? 
e.g. https://www.npmjs.com/package/connection-string

> Since I didn't found Coding Standards for this repo, please let me know if you have suggestions on how to improve the code.

Yeah, i will add eslint quickly.

**Comment by kirrg001** [comment]
https://github.com/TryGhost/knex-migrator/commit/3392ffde7a6345e97320a36c245465e4b87b097d

**Comment by he8us** [comment]
> Did you test or consider any existing libraries?
> e.g. https://www.npmjs.com/package/connection-string

No, I did not at that time.

I just tried but connection-string don't handle correctly the [official SQLite URI description](https://sqlite.org/uri.html) nor the examples given in the [sqlite3_open](https://sqlite.org/c3ref/open.html#urifilenamesinsqlite3open) documentation.

I can force the string to follow the pattern `sqlite://PATH` which would give:

* `sqlite://data.db` for a relative path.
* `sqlite:///home/ghost/data.db` for an absolute path.

It would be easier to manage but more restrictive.

In the end, the choice is yours, tell me what you think.


> 3392ffd

I already updated the files to be eslint compliant but I needed to add `'mocha': true` in order for eslint to recognize `describe` and `it`.

**Comment by he8us** [comment]
Ping!

Should I use connection-string package?

**Comment by kirrg001** [comment]
@he8us Sorry for late response. If you rebase, i'll merge this through.

**Comment by he8us** [comment]
@kirrg001 I'm sorry too. I just rebased

**Comment by kirrg001** [comment]
@he8us Thanks. Did you consider open a PR to https://www.npmjs.com/package/connection-string? Sorry for asking again 😀

**Comment by he8us** [comment]
I had, but I have a newborn which takes lot of my time so I didn't looked closely what to change.

**Comment by kirrg001** [comment]
@he8us no problem :) i'll take that over

**Comment by kirrg001** [comment]
https://github.com/vitaly-t/connection-string/issues/1

Support for this was added @he8us

**Comment by kirrg001** [comment]
Thanks for all your work and effort. I will close the PR,  because the PR is from 2017 and I haven't gotten a reply in the last 20 days. A new PR is very welcome 🙂

**Pull request closed without merging**
